#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define _QWERTY 0
#define _MOVEMENT 1
#define _MEDIA 2
#define _MOUSE 3
#define _NUMBERS 4
#define _SYMBOLS 5
#define _FKEYS 6

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_QWERTY] = LAYOUT_split_3x6_3( \
		TG(_MEDIA), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO, \
		TG(_MOUSE), LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RCTL_T(KC_K), RALT_T(KC_L), RGUI_T(KC_QUOT), KC_NO, \
		LT(_MEDIA,KC_TAB), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_NO, \
		LT(_MOUSE,KC_ESC), LT(_MOVEMENT,KC_SPC), LT(_MEDIA,KC_TAB), LT(_SYMBOLS,KC_ENT), LT(_NUMBERS,KC_BACKSPACE), LT(_FKEYS,KC_DEL)\
	),
	[_MOVEMENT] = LAYOUT_split_3x6_3( \
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, KC_NO,\
		KC_NO, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_CAPS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO,\
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_ENT, KC_BSPC, KC_DEL\
	),
	[_MEDIA] = LAYOUT_split_3x6_3( \
		TG(_MEDIA), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO,\
		KC_NO, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_MRWD, KC_VOLD, KC_VOLU, KC_MFFD, KC_NO,\
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_NO, KC_NO, KC_NO, KC_MSTP, KC_MPLY, KC_MUTE
	),
	[_MOUSE] = LAYOUT_split_3x6_3( \
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, KC_NO, \
		TG(_MOUSE), KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_NO, \
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_NO,\
		KC_NO, KC_NO, KC_NO, KC_BTN2, KC_BTN1, KC_BTN3\
	),
	[_NUMBERS] = LAYOUT_split_3x6_3( \
		KC_NO, KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_NO, KC_SCLN, KC_4, KC_5, KC_6, KC_EQL, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_NO,\
		KC_MINS, KC_GRV, KC_1, KC_2, KC_3, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_DOT, KC_0, KC_MINS, KC_NO, KC_NO, KC_NO\
	),
	[_SYMBOLS] = LAYOUT_split_3x6_3( \
		KC_NO, KC_LCBR, KC_AMPR, KC_ASTR, KC_LPRN, KC_RCBR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_NO, KC_COLN, KC_DLR, KC_PERC, KC_CIRC, KC_PLUS, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_NO,\
		KC_UNDS, KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_PIPE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_LPRN, KC_RPRN, KC_UNDS, KC_NO, KC_NO, KC_NO\
	),
	[_FKEYS] = LAYOUT_split_3x6_3( \
		KC_NO, KC_F12, KC_F7, KC_F8, KC_F9, KC_PSCR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_NO, KC_F11, KC_F4, KC_F5, KC_F6, KC_SCRL, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_NO,\
		KC_TAB, KC_F10, KC_F1, KC_F2, KC_F3, KC_PAUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,\
		KC_APP, KC_SPC, KC_TAB, KC_NO, KC_NO, KC_NO\
	)
};

#ifdef ENCODER_ENABLE
bool encoder_update_user(uint8_t index, bool clockwise) {
    if (!encoder_update_user(index, clockwise)) {
        return false;
    }
    // 0 is left-half encoder,
    // 1 is right-half encoder
    if (index == 0) {
        if (layer_state_is(_MOUSE)) {
            // Etch a sketch mouse
            if (clockwise) {
                tap_code(KC_MS_U);
            } else {
               tap_code(KC_MS_D);
            }
        } else if (layer_state_is(_MEDIA)) {
            // Volume
            if (clockwise) {
	       rgb_matrix_step();
            } else {
	       rgb_matrix_step_reverse();
            }
        } else {
            // Volume
            if (clockwise) {
                tap_code(KC_VOLU);
            } else {
               tap_code(KC_VOLD);
            }
        }
    } else if (index == 1) {
        if (layer_state_is(_MOUSE)) {
            // Etch a sketch mouse
            if (clockwise) {
                tap_code(KC_MS_R);
            } else {
               tap_code(KC_MS_L);
            }
        } else if (layer_state_is(_MEDIA)) {
            // Volume
            if (clockwise) {
                rgb_matrix_increase_hue();
            } else {
                rgb_matrix_decrease_hue();
            }
        } else {
            // Page up/Page down
            if (clockwise) {
                tap_code(KC_PGDN);
            } else {
                tap_code(KC_PGUP);
            }
	}
    }
    return true; 
    // If you return true, this will allow the keyboard level code to run, as well. 
    //Returning false will override the keyboard level code. Depending on how the keyboard level function is set up.
}
#endif
